/**
 * Write the sync registry out as JSON, for the iOS app's parity test.
 *
 * The phone cannot ask the Mac which fields exist — it builds its SQLite
 * schema before it has ever paired. So the registry is duplicated in Swift,
 * and duplication that nothing checks is duplication that drifts. This dumps
 * the authoritative copy to a fixture; `EntityParityTests` on the Swift side
 * fails when the two no longer agree.
 *
 *     npm -w @soloops/api run sync:registry
 *
 * Run it after changing SYNC_ENTITIES, and commit the fixture with the change.
 */

import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import {
  DELETE_SIDE_EFFECTS,
  SYNC_ENTITIES,
  SYNC_ENTITY_NAMES,
} from '../src/services/syncEntities.js'

const target = resolve(
  import.meta.dirname,
  '../../ios/SoloopsKit/Tests/SoloopsKitTests/Fixtures/registry.json',
)

const registry = {
  note: 'Generated by apps/api/scripts/exportSyncRegistry.ts — do not edit by hand.',
  entities: SYNC_ENTITY_NAMES.map((name) => {
    const spec = SYNC_ENTITIES[name]
    return {
      name,
      rank: spec.rank,
      required: [...spec.required].sort(),
      // Sorted so the fixture does not churn when a field is inserted in the
      // middle of the TypeScript object.
      fields: Object.fromEntries(
        Object.entries(spec.fields).sort(([a], [b]) => a.localeCompare(b)),
      ),
      sideEffects: DELETE_SIDE_EFFECTS[name]
        .map((effect) => ({ kind: effect.kind, entity: effect.entity, fk: effect.fk }))
        .sort((a, b) => `${a.entity}.${a.fk}`.localeCompare(`${b.entity}.${b.fk}`)),
    }
  }),
}

mkdirSync(dirname(target), { recursive: true })
writeFileSync(target, `${JSON.stringify(registry, null, 2)}\n`)
console.log(`Registry geschrieben: ${target}`)
console.log(`${registry.entities.length} Entitäten`)
